version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    env_file: 
      - siikr.env
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"

  php:
    build:
      context: .
      dockerfile: docker/php-fpm.Dockerfile
    ports:
      - "8080:80"
    env_file: 
      - siikr.env
    depends_on: 
      - postgres
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
