
version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    image: my-postgres:latest
    env_file: 
      - siikr.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./siikr/siikr_db_setup.sql:/docker-entrypoint-initdb.d/01_siikr_db_setup.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  php:
    build:
      context: .
      dockerfile: docker/php-fpm.Dockerfile
    image: my-php-fpm:latest
    ports:
      - "8080:80"
    env_file: 
      - siikr.env
    depends_on: 
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

